---
title: "Lab 10"
output: html_notebook
---

```{r load lib and data train test split}
library(tidyverse)
library(AmesHousing)
library(car)

ames <- make_ordinal_ames()

set.seed(123)
ames <- ames %>% mutate(id = row_number())
train <- ames %>% sample_frac(0.7)
test <- anti_join(ames, train, by = 'id')
```
```{r}
summary(train)
```



## Check Correlations
```{r set ames_num}
train_num <- train %>% 
  # select_if(is.numeric) %>% 
  select(-c("id"))
```

```{r corr table}
cor.dat <- train_num %>% correlation::correlation()
cor.dat %>% filter((cor.dat$r > .5) | (cor.dat$r < -.5))
```


```{r}
lm.1 <- lm(Sale_Price~. - Garage_Cond - Bsmt_Cond - MS_SubClass - Exterior_2nd - 
             First_Flr_SF- Second_Flr_SF-Low_Qual_Fin_SF-Condition_1-Condition_2 - 
             Garage_Qual -Utilities - Misc_Feature - BsmtFin_Type_1, data=train_num)
# summary(lm.1)
alias(lm.1)$Complete
```

```{r}
vif(lm.1)
```

```{r}
# Longitude, Latitude
train_sel <-  train %>% select(-c("Longitude", "Latitude", "BsmtFin_Type_2", "Overall_Qual","Exter_Qual",
                                  "BsmtFin_Type_1","Bsmt_Qual", "Heating","Bsmt_Full_Bath","Bsmt_Half_Bath",
                                  "Bsmt_Exposure", "Garage_Cars", "Kitchen_AbvGr", "Bedroom_AbvGr", "Three_season_porch", "Enclosed_Porch",
                                  "Pool_Area", "Open_Porch_SF", "Wood_Deck_SF", "Sale_Type"))
empty.mod <- lm(Sale_Price ~ 1, data = train_sel)
full.mod <- lm(Sale_Price ~ ., data = train_sel)
'for.mod <- step(empty.mod,
                scope = list(
                  lower = empty.mod,
                  upper = full.mod
                ),
                direction = "both",
                steps = 12,
                trace = FALSE)'
```
```{r}
lm.2 <- step(empty.mod,
                scope = list(
                  lower = empty.mod,
                  upper = full.mod
                ),
                direction = "forward",
                steps = 12,
                trace = FALSE)

```
```{r}
lm.2 %>% summary()
```
```{r}
lm.2 %>% plot()
```

```{r}
lm.2.log <- lm(log(Sale_Price) ~ Neighborhood + Gr_Liv_Area + Kitchen_Qual + 
    MS_SubClass + Year_Built + Roof_Matl + Total_Bsmt_SF + Misc_Feature + 
    Bsmt_Unf_SF + Overall_Cond + Sale_Condition + Mas_Vnr_Area, data=train_sel)
lm.2.log %>% summary()
```
```{r}
lm.2.log %>% plot()
```
```{r}
ggplot(lm.2.log ,aes(x=hatvalues(lm.2.log),y=rstudent(lm.2.log)))+
  geom_point()+
  geom_hline(yintercept=3)+
  geom_vline(xintercept=1) +
  labs(x="Hat Values",y="Residuals")
```
```{r}
D.cut=4/(nrow(train_sel)-11) 
n.index=seq(1,nrow(train_sel))

ggplot(lm.2.log, aes(n.index, cooks.distance(lm.2.log))) +
  geom_point() +
  geom_hline(yintercept = D.cut)
```


```{r}
train_sel$a <- (cooks.distance(lm.2.log) > D.cut) & (rstudent(lm.2.log) > 3 | rstudent(lm.2.log) < -3)

```

```{r}
train_filtered <-  train_sel %>% filter(a != TRUE)
train_filtered %>% nrow()
```

```{r}
lm.3 <- lm(log(Sale_Price) ~ Neighborhood + Gr_Liv_Area + Kitchen_Qual + 
    MS_SubClass + Year_Built + Roof_Matl + Total_Bsmt_SF + Misc_Feature + 
    Bsmt_Unf_SF + Overall_Cond + Sale_Condition + Mas_Vnr_Area, data = train_filtered)
summary(lm.3) %>% print()
lm.3 %>% plot()
```
```{r}
train_filtered <- train_filtered %>% select(-c("id","a"))
```

```{r}

sale_price <- train_filtered %>% select(c("Sale_Price"))
train_filtered_cent <- as.data.frame(lapply(train_filtered %>% select(-c("Sale_Price")), function(x) {
  if(is.numeric(x)) scale(x, scale = FALSE) else x
}))

train_filtered_cent$Sale_Price <- sale_price$Sale_Price
```

```{r}
empty.mod <- lm(Sale_Price ~ 1, data = train_filtered_cent)
full.mod <- lm(Sale_Price ~ ., data = train_filtered_cent)

lm.4 <- step(empty.mod,
                scope = list(
                  lower = empty.mod,
                  upper = full.mod
                ),
                direction = "forward",
                steps = 12,
                trace = FALSE)

```
```{r}
lm.4 %>% plot()
```
```{r}
train_filtered_cent$a <- (cooks.distance(lm.4) > D.cut) & (rstudent(lm.4) > 3 | rstudent(lm.4) < -3)
train_filtered_cent2 <- train_filtered_cent %>% filter(a != TRUE)
```

```{r}
empty.mod <- lm(Sale_Price ~ 1, data = train_filtered_cent2)
full.mod <- lm(Sale_Price ~ ., data = train_filtered_cent2)

lm.5 <- step(empty.mod,
                scope = list(
                  lower = empty.mod,
                  upper = full.mod
                ),
                direction = "forward",
                steps = 12,
                trace = FALSE)
```

```{r}
lm.5 %>% summary()
formula.2 <-  log(Sale_Price) ~ Neighborhood + Gr_Liv_Area + Kitchen_Qual + 
    Total_Bsmt_SF + MS_SubClass + Bsmt_Unf_SF + Year_Built + 
    Overall_Cond + Mas_Vnr_Area + Sale_Condition + Pool_QC + 
    Garage_Area
lm.6.log <- lm(formula.2, data=train_filtered_cent2)
lm.6.log %>% AIC()
```
```{r}
vif(lm.6.log)
```





```{r}
empty.mod <- lm(log(Sale_Price) ~ 1, data = train_filtered_cent)
full.mod <- lm(log(Sale_Price) ~ ., data = train_filtered_cent)

lm.7 <- step(empty.mod,
                scope = list(
                  lower = empty.mod,
                  upper = full.mod
                ),
                direction = "forward",
                steps = 12,
                trace = FALSE)

```

```{r}
lm.7 %>% summary()
```



```{r}
final_12 <- train_filtered_cent %>% select(c('Sale_Price', 'Neighborhood' , 'Gr_Liv_Area' , 'Total_Bsmt_SF' , 
    'Overall_Cond' , 'Year_Built' , 'MS_SubClass' , 'Bsmt_Unf_SF' , 'Kitchen_Qual' , 
    'Sale_Condition' , 'Garage_Area' , 'Fireplaces' , 'Condition_1'))
empty.mod <- lm(Sale_Price ~ 1, data = final_12)
full.mod <- lm(Sale_Price ~ .^2, data = final_12)

lm.8 <- step(empty.mod,
                scope = list(
                  lower = empty.mod,
                  upper = full.mod
                ),
                direction = "forward",
                steps = 12,
                trace = FALSE)

```

```{r}
final.lm <- lm(log(Sale_Price) ~ Neighborhood + Gr_Liv_Area + Kitchen_Qual + 
    Total_Bsmt_SF + Bsmt_Unf_SF + Overall_Cond + Year_Built + 
    MS_SubClass + Neighborhood:Gr_Liv_Area + Kitchen_Qual:Total_Bsmt_SF + 
    Neighborhood:Year_Built + Kitchen_Qual:MS_SubClass, data = train)
final.lm %>% plot()
```
```{r}
shapiro.test(residuals(final.lm))
```
```{r}
ggplot(final.lm, aes(x = .resid)) +
  geom_histogram()
  
```





```{r}
t.1 <-  train %>% select(c('Sale_Price', 'Neighborhood' , 'Gr_Liv_Area' , 'Total_Bsmt_SF' , 
    'Overall_Cond' , 'Year_Built' , 'MS_SubClass' , 'Bsmt_Unf_SF' , 'Kitchen_Qual' , 
    'Sale_Condition' , 'Garage_Area' , 'Fireplaces' , 'Condition_1'))

lm(log(Sale_Price) ~ Neighborhood + Gr_Liv_Area + Kitchen_Qual + 
    Total_Bsmt_SF + Bsmt_Unf_SF + Overall_Cond + Year_Built + 
    MS_SubClass + Neighborhood:Gr_Liv_Area + Kitchen_Qual:Total_Bsmt_SF + 
    Neighborhood:Year_Built + Kitchen_Qual:MS_SubClass,
    data= t.1) %>% summary()

```
```{r}
lm.hp <- lm(log(Sale_Price) ~ Neighborhood + Gr_Liv_Area + I(Gr_Liv_Area^2) +
                 I(Gr_Liv_Area^3) + I(Gr_Liv_Area^4) + I(Gr_Liv_Area^5) + 
                 I(Gr_Liv_Area^6) + I(Gr_Liv_Area^7) +Garage_Area +
                 Kitchen_Qual:MS_SubClass + Overall_Cond + Year_Built, data=train) 
lm.hp %>% summary()
lm.hp %>% plot()
lm.hp %>% AIC()


```






